### ISSUE TITLE
Whats next?

### ISSUE THREAD

**Issue by rdsubhas** [devopsbookmarks/devopsbookmarks.com#109]
Opening an issue to find out what people would like to see in the next big release of devopsbookmarks.com. I'd definitely want more discoverability - like "Recently Added", "Recently Updated", etc :) Let's have a poll!

tagging @scottmuc :+1:

**Comment by scottmuc** [comment]
Not sure if it's feature creep but I would like to add links to books and/or articles. I could imagine that becoming too busy though.

A newness filter is interesting, and definitely useful.

One part that I find useful when it comes to researching tools is knowing how long they've been around. Is that another attribute that we can add?

**Comment by silopolis** [comment]
Hi,

First congrats for this nice project !

2 ideas:
   * a link to projects openhub.net pages
   * add "API" and/or I/O protocols/formats supported by projects to
provide interroperability/composability informations

Thanks


2015-10-29 11:51 GMT+01:00 Scott Muc <notifications@github.com>:

> Not sure if it's feature creep but I would like to add links to books
> and/or articles. I could imagine that becoming too busy though.
>
> A newness filter is interesting, and definitely useful.
>
> One part that I find useful when it comes to researching tools is knowing
> how long they've been around. Is that another attribute that we can add?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/devopsbookmarks/devopsbookmarks.com/issues/109#issuecomment-152145536>
> .
>



-- 
--
Jérémie Tarot
http://about.me/silopolis

**Comment by ruf-io** [comment]
Hi! This project is really great.

What about pulling in github metrics for tools that have a repo listed?  Would be nice to get a sense of whether a project is still actively maintained, etc...

**Comment by leonardodavinte** [comment]
It would be interesting a search button on the home page.
