### ISSUE TITLE
Deployments are broken

### ISSUE THREAD

**Issue by scottmuc** [devopsbookmarks/devopsbookmarks.com#111]
SnapCI has been breaking deploys since August. Not sure what changed with Heroku, but assuming that we need to change something to fix the deploy.

/cc @rdsubhas

**Comment by rdsubhas** [comment]
```
Cedar-10 is deprecated. Please update to Cedar-14: https://devcenter.heroku.com/articles/cedar-14-migration
```

Doing it :+1:

**Comment by rdsubhas** [comment]
Related to #106

**Comment by rdsubhas** [comment]
Done

**Comment by scottmuc** [comment]
Hah! awesome! Shows how much I pay attention to those announcements :+1:
