### ISSUE TITLE
Policy for Removals - (Gitorious)

### ISSUE THREAD

**Issue by ruf-io** [devopsbookmarks/devopsbookmarks.com#112]
[Gitorious](http://getgitorious.com/), listed on devopsbookmarks [here](http://www.devopsbookmarks.com/scm), has been bought by and merged into [GitLab](https://about.gitlab.com/2015/03/03/gitlab-acquires-gitorious/), what's the process when a tool disappears (or in this case, gets merged into another tool?)

Do we just take it down?

**Comment by scottmuc** [comment]
The goal is to make the website a living document that is a snapshot of now, not a timeline. So with that context, it would make sense to me to remove Gitorious and update GitLab with a note that this has happened.
