### ISSUE TITLE
Getting an error when running vagrant ssh -c /vagrant/script/server

### ISSUE THREAD

**Issue by madhuakula** [devopsbookmarks/devopsbookmarks.com#119]
$ vagrant ssh -c /vagrant/script/server
- dirname /vagrant/script
- cd /vagrant
- npm install
  npm WARN deprecated This version of npm lacks support for important features,
  npm WARN deprecated such as scoped packages, offered by the primary npm
  npm WARN deprecated registry. Consider upgrading to at least npm@2, if not the
  npm WARN deprecated latest stable version. To upgrade to npm@2, run:
  npm WARN deprecated
  npm WARN deprecated   npm -g install npm@latest-2
  npm WARN deprecated
  npm WARN deprecated To upgrade to the latest stable version, run:
  npm WARN deprecated
  npm WARN deprecated   npm -g install npm@latest
  npm WARN deprecated
  npm WARN deprecated (Depending on how Node.js was installed on your system, you
  npm WARN deprecated may need to prefix the preceding commands with `sudo`, or if
  npm WARN deprecated on Windows, run them from an Administrator prompt.)
  npm WARN deprecated
  npm WARN deprecated If you're running the version of npm bundled with
  npm WARN deprecated Node.js 0.10 LTS, be aware that the next version of 0.10 LTS
  npm WARN deprecated will be bundled with a version of npm@2, which has some small
  npm WARN deprecated backwards-incompatible changes made to `npm run-script` and
  npm WARN deprecated semver behavior.

> devops@0.0.1 postinstall /vagrant
> grunt build

module.js:340
    throw err;
          ^
Error: Cannot find module 'coffee-script'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/node_modules/grunt/lib/grunt.js:16:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

npm ERR! devops@0.0.1 postinstall: `grunt build`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the devops@0.0.1 postinstall script.
npm ERR! This is most likely a problem with the devops package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     grunt build
npm ERR! You can get their info via:
npm ERR!     npm owner ls devops
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-76-generic
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /vagrant
npm ERR! node -v v0.10.41
npm ERR! npm -v 1.4.29
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /vagrant/npm-debug.log
npm ERR! not ok code 0
Connection to 127.0.0.1 closed.

**Comment by rdsubhas** [comment]
@madhuakula Thanks for reporting, maybe because we're still running Node 0.10 😱 Will check this out today. Meanwhile, if you're planning to submit a new tool/framework - please go ahead and just add the JSON file and send us a pull request. The CI will make sure nothing bad like this happens :)

**Comment by madhuakula** [comment]
Thanks @rdsubhas , Actually I am looking into how you are making this website. I wanted to use similar thing for Security Tools.

Can you help me about the setup?

Thanks 
Madhu Akula

**Comment by scottmuc** [comment]
Hi @madhuakula, `vagrant` has been removed in favour of a `docker` workflow for local testing. Let us know if you have any issues with that.
