### ISSUE TITLE
Topic/Tag to consider: Test Frameworks

### ISSUE THREAD

**Issue by RamblingCookieMonster** [devopsbookmarks/devopsbookmarks.com#134]
Hi!

Love this idea! Curious if you'd be interested in including testing frameworks?

For example:

``` json
[{
  "name": "Test Frameworks",
  "slug": "testing",
  "include_tags": [ "testing" ]
}
```

Cheers!

**Comment by scottmuc** [comment]
@RamblingCookieMonster interesting, I think this could apply to testing of infrastructure pieces. Something like [Serverspec](http://serverspec.org/) fits, but perhaps generic `rspec` doesn't.

What other examples do you have in mind?

**Comment by RamblingCookieMonster** [comment]
@scottmuc good question.  Tools like [Test Kitchen](http://kitchen.ci/), Serverspec, [Inspec](https://github.com/chef/inspec), seem like they might be worth including?

'Test framework' might not be the best descriptor, just threw it out there.

Individual testing suites (e.g. Pester ; ) might clutter things up, but, they seem fairly integral to our practice?

Cheers!
