### ISSUE TITLE
Topic/Tag to consider: Auditing

### ISSUE THREAD

**Issue by mikhailadvani** [devopsbookmarks/devopsbookmarks.com#151]
Maybe as an extension of logging/monitoring

**Comment by scottmuc** [comment]
Yeah, this is a good suggestion. I'll take a look and see how we can incorporate auditing into the website.

**Comment by rdsubhas** [comment]
Hi folks, we have a "Security and Hardening" topic - does auditing also fall under the same umbrella?

**Comment by scottmuc** [comment]
I like audit on it's own. You can audit code for licensing compliance. Or you can audit for versions of dependencies to see if you have a comprimised version of openssl.

@mikhailadvani what kind of tools did you have in mind?

**Comment by mikhailadvani** [comment]
- SecurityMonkey
- Scout2
