### ISSUE TITLE
Internal error exploring tags

### ISSUE THREAD

**Issue by mariancuadra** [devopsbookmarks/devopsbookmarks.com#237]
Hi,

I'm not sure if it's here right place to report this bug, if not, I'm sorry!

When I try to navigate through tags (except meta tags which are external links) in https://www.devopsbookmarks.com/, all of theme returns Internal server error.

![internal error](https://user-images.githubusercontent.com/105197227/232691161-abb4091a-00a4-44f2-8220-a888d83bae86.png)

Regards!

**Comment by scottmuc** [comment]
Thanks @mariancuadra ! I thought I fixed this, but it appears I wasn't comprehensive enough. I'll look at this right now.

**Comment by mariancuadra** [comment]
Thanks @scottmuc!
