### ISSUE TITLE
RFC: Replace topics with behaviours

### ISSUE THREAD

**Issue by scottmuc** [devopsbookmarks/devopsbookmarks.com#70]
I blogged about the [concerns I have](http://scottmuc.com/what-makes-something-a-devops-tool/) about this website. Not only should this be a place of discovery but a place that reinforces the core concepts of devops. A list of tools dilutes it, in my humble opinion.

Some ideas around behaviours are:
- Infrastructure as Code (eg: chef, ansible, terraform, vagrant)
- Data Informed Decisions (graphite)
- Situational Awareness (logstash, kibana, nagios)
- Knowledge Sharing (apiary, asciidoc)

I keep on going back to CAMS (Culture, Automation, Metrics, and Sharing) as the core components of devops. The way the topics are listed now, they are too implementation specific. 

Essentially, what's driving me crazy is that I know there's more to devops than a list of tools. As I see it now, this website does a good job of displaying some tools. It doesn't explain why these are devops tools nor what it means to be a devops tool.

**Comment by mnemotronic** [comment]
To paraphrase Suzie Orman:
 _ People First
 _ Then processes
 _ Then tools

I know some folks understand the need to prioritize the integration and education of, and acceptance by, internal culture.  If you've ever heard anyone in your organization refer to "silos", "internal politics" or "tribal knowledge" then you've got a cultural challenge.  Failure to address this will lead to less success in the long run.
